import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>/pages/index.tsx</h1>
        <ul>
          <li>
            <a href="/sub">/pages/sub/index.tsx</a>
          </li>
          <li>
            <a href="/sub/about">/pages/sub/about.tsx</a>
          </li>
          <li>
            <a href="/sub/1">/pages/sub/[id].tsx</a>
          </li>
          <li>
            <a href="/sub/2">/pages/sub/[id].tsx</a>
          </li>
        </ul>
      </div>
    </>
  );
}
