import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useContext } from "react";
import PortfolioContext from "../context/context";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { prefix } = useContext(PortfolioContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>/pages/index.tsx</h1>
        <h2>click!</h2>
        <ul>
          <li>
            <Link href={`${prefix}/sub`}>/pages/sub/index.tsx</Link>
          </li>
          <li>
            <Link href={`${prefix}/sub/about`}>/pages/sub/about.tsx</Link>
          </li>
          <li>
            <Link href={`${prefix}/sub/1`}>/pages/sub/[id].tsx</Link>
          </li>
          <li>
            <Link href={`${prefix}/sub/2`}>/pages/sub/[id].tsx</Link>
          </li>
        </ul>
      </div>
    </>
  );
}
